name: Auto-Compile
on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps and build
        run: npm ci --only=production && npm run build
      - name: Automatically build action
        uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
